languageCode = "en-us"
title = "Brett-Whitehead family history"
newContentEditor = "ggvr"
theme = "tale"
baseURL = "matthew-brett.github.io/brett-whitehead/"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'pandoc$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
